---
# tasks file for activemq
- name: Creates /etc/dd-agent/conf.d/ directory
  file:
    path: /etc/dd-agent/conf.d/
    state: directory
    
- name: Template a file to /etc/activemq.d/conf.yaml
  ansible.builtin.template:
    src: templates/activemq.yaml.j2
    dest: /etc/dd-agent/conf.d/conf.yaml
    owner: 'dd-agent'
    group: root
    mode: '0600'
